import React, { createContext, useContext, useState } from 'react';

// ── Translation dictionary ────────────────────────────────────────────────────

const T = {
  ID: {
    // Map modal
    mapTitle:  'Lokasi Kami',
    mapEmpty:  'Peta belum dikonfigurasi. Hubungi administrator.',
    mapClose:  'Tutup',

    // Nav (bottom bar)
    'nav.catalog': 'Katalog',
    'nav.cart':    'Keranjang',
    'nav.orders':  'Pesanan',

    // Common
    'common.back':   'Kembali',
    'common.close':  'Tutup',
    'common.later':  'Nanti',
    'common.none':   'Tidak ada',

    // Browse page
    'search.placeholder':      'Cari produk...',
    'search.storePlaceholder': 'Cari toko...',
    'filter.all':              'Semua',
    'filter.inStockOnly':      'Stok tersedia saja',
    'filter.productCount':     '{count} produk',
    'browse.allProducts':      'Semua Produk',
    'browse.selectedProducts': 'Produk Terpilih',
    'browse.items':            '{count} item',
    'browse.products':         '{count} produk',
    'browse.backToStores':     '← Kembali ke Toko',
    'browse.byProduct':        '🏷️ Per Produk',
    'browse.byStore':          '🏪 Per Toko',
    'browse.noStores':         'Tidak ada toko di lantai ini',
    'browse.tryOtherFloor':    'Coba lantai lain',
    'browse.searchWishlist':    'Cari di wishlist...',
    'browse.myWishlist':       'Wishlist Saya',
    'browse.itemsSaved':       'produk tersimpan',
    'browse.wishlistEmpty':    'Wishlist masih kosong',
    'browse.noWishlistMatch':  'Produk tidak ditemukan di wishlist.',
    'browse.exploreCatalog':   'Jelajahi Produk',
    'browse.scanAddedToCart':  'ditambahkan ke keranjang',
    'browse.scanNotFound':     'Produk tidak ditemukan. Coba scan ulang.',
    'browse.scanQRTitle':      'Scan QR Produk',
    'browse.scanQRHint':       'Arahkan kamera ke QR code produk',
    'product.notFound':        'Produk tidak ditemukan',
    'product.tryOther':        'Coba kategori atau kata kunci lain',
    'product.outOfStock':      'Stok Habis',
    'product.added':           '✓ Ditambah',
    'product.addToCart':       '+ Keranjang',
    'product.loadMore':        'Muat lebih banyak',

    // Product detail
    'product.notFoundDetail':   'Produk tidak ditemukan.',
    'back':                     '← Kembali',
    'product.booth':            'Booth',
    'product.location':         'Lokasi',
    'product.stock':            'Stok',
    'product.addedFull':        '✓ Ditambahkan ke Keranjang',
    'product.addToCartFull':    'Tambah ke Keranjang',
    'product.detail.category':  'KATEGORI',
    'product.detail.description':'DESKRIPSI',
    'product.detail.noDesc':    'Belum ada deskripsi produk',
    'product.detail.floor':     'Lantai {n}',
    'product.detail.added':     'Ditambahkan',

    // Cart
    'cart.stockAvailablePrompt': 'Stok sudah tersedia! Pindahkan ke keranjang?',
    'cart.moveToCart':           'Pindahkan ke Keranjang',
    'cart.stockAvailable':       '✓ Stok Tersedia',
    'cart.waitingForStock':      '⏳ Menunggu Stok',
    'cart.savedForLater':        'Disimpan untuk Nanti',
    'cart.itemCount':            '{count} barang',
    'cart.voucherSection':       'Voucher Diskon',
    'cart.waitingWarningTitle':  '{count} barang menunggu konfirmasi stok',
    'cart.waitingWarningBody':   'Kunjungi booth untuk konfirmasi, atau lanjutkan checkout hanya untuk barang yang tersedia. Barang yang menunggu akan disimpan ke Wishlist secara otomatis.',
    'cart.helperModeWarning':    'Mode Helper Input aktif. Pemesanan hanya dapat dilakukan melalui petugas booth.',
    'cart.approveModeWarning':   'Pesanan Anda akan menunggu persetujuan dari petugas booth. Stok dan timer mulai berjalan setelah disetujui.',
    'cart.itemLimitWarning':     'Maksimal {max} item per order. Saat ini {current} item — kurangi sebelum checkout.',
    'cart.subtotal':             'Subtotal',
    'cart.discount':             'Diskon',
    'cart.taxLine':              'PPN {rate}%',
    'cart.estimatedTotal':       'Estimasi total ({count} barang tersedia)',
    'cart.exceedsLimit':         'Melebihi batas',
    'cart.contactBooth':         'Hubungi petugas booth',
    'cart.submitForApproval':    'Kirim ke Antrian Persetujuan',
    'cart.orderAvailable':       'Pesan Barang Tersedia ({count} barang)',
    'cart.allItemsWaiting':      'Semua barang menunggu konfirmasi',
    'cart.unconfirmedNote':      'Belum dikonfirmasi booth · tanyakan langsung atau hapus',
    'cart.approvalTitle':        'Sebagian barang belum dikonfirmasi stoknya',
    'cart.approvalDesc':         'Barang berikut masih menunggu konfirmasi ketersediaan dari booth.',
    'cart.readyToProcess':       'Siap Diproses',
    'cart.noItems':              'Tidak ada',
    'cart.awaitingConfirmation': 'Menunggu Konfirmasi',
    'cart.onHoldSavedNote':      'Barang yang menunggu konfirmasi akan disimpan ke Wishlist — tidak dihapus. Anda akan diberitahu lewat notifikasi saat stok tersedia.',
    'cart.totalReadyItems':      'Total {count} barang siap diproses',
    'cart.allOnHold':            'Semua barang sedang menunggu konfirmasi stok.',
    'cart.checkoutUnavailable':  'Checkout tidak dapat dilanjutkan saat ini.',
    'cart.continueCheckout':     'Ya, Lanjutkan Checkout',
    'cart.title':                'Keranjang ({count} item)',
    'cart.empty.title':   'Keranjang kosong',
    'cart.empty.desc':    'Tambahkan produk dari katalog',
    'cart.toCatalog':     'Ke Katalog →',
    'cart.total':         'Total Pembayaran',
    'cart.pendingNote':   'Pesanan akan berlaku selama 30 menit. Segera bayar ke kasir.',
    'cart.checkout':      'Buat Pesanan',
    'cart.checkoutError': 'Checkout gagal. Coba lagi.',

    // Order history
    'orders.title':       'Riwayat Pesanan',
    'orders.empty.title': 'Belum ada pesanan',
    'orders.empty.desc':  'Yuk, mulai belanja di katalog!',
    'orders.toCatalog':   'Ke Katalog →',

    // Order tracking
    'order.notFound':     'Pesanan tidak ditemukan.',
    'order.backHistory':  '← Riwayat Pesanan',
    'order.showQR':       'Tunjukkan QR ini ke kasir',
    'order.cancelBtn':    'Batalkan Pesanan',
    'order.cancelTitle':  'Batalkan Pesanan?',
    'order.cancelBody':   'Pesanan {id} akan dibatalkan dan stok dikembalikan.',
    'order.cancelNo':     'Tidak',
    'order.cancelYes':    'Ya, Batalkan',
    'order.refresh':      'Perbarui',
    'order.refreshing':   'Memperbarui...',

    // Payment confirmed (C7)
    'confirmed.title':         'Pembayaran Berhasil!',
    'confirmed.subtitle':      'Barang Anda sedang disiapkan di booth',
    'confirmed.txnId':         'ID Transaksi',
    'confirmed.totalPaid':     'Total Dibayar',
    'confirmed.payment':       'Metode Bayar',
    'confirmed.datetime':      'Tanggal & Waktu',
    'confirmed.nonReturnable': 'Semua penjualan bersifat final dan tidak dapat dikembalikan.',
    'confirmed.cta':           'Lihat Struk & Slip Pengambilan',
    'confirmed.ctaHint':       'Ambil barang di booth tenant',

    // Receipt & pickup (C8)
    'receipt.sectionReceipt': 'STRUK PEMBAYARAN',
    'receipt.sectionPickup':  'INSTRUKSI PENGAMBILAN',
    'receipt.total':          'Total',
    'receipt.done':           'Selesai ✓',
    'receipt.ready':          'Siap',
    'receipt.cta':            'Lacak Pengambilan Barang',

    // Pickup status (C9)
    'pickup.infoBanner':   'Kunjungi setiap booth dan tunjukkan kode QR Anda. Status diperbarui otomatis.',
    'pickup.done':         'Selesai ✓',
    'pickup.ready':        'Siap',
    'pickup.preparing':    'Menyiapkan',
    'pickup.collected':    'Sudah Diambil',
    'pickup.items':        'barang',
    'pickup.allDone':      'Semua barang sudah diambil! 🎉',
    'pickup.showBarcode':  'Tampilkan Barcode Transaksi',
    'pickup.modalTitle':   'Barcode Transaksi',

    // Checkout success
    'checkout.created':  'Pesanan Dibuat!',
    'checkout.showQR':   'Tunjukkan kode QR ini ke kasir untuk pembayaran',
    'checkout.qrMissing':'QR Code tidak tersedia',
    'checkout.txnId':    'ID Transaksi',
    'checkout.total':    'Total',
    'checkout.payIn':    '⏰ Bayar dalam {mins}:{secs} menit',
    'checkout.expired':  '⚠️ Pesanan telah kadaluarsa',
    'checkout.track':    'Lacak Pesanan',
    'checkout.continue': 'Lanjut Belanja',

    // Login
    'login.title':        'Masuk',
    'login.subtitle':     'Amazing Toys Fair 2026',
    'login.phone':        'Nomor Telepon',
    'login.phonePh':      '08xxxxxxxxxx',
    'login.submit':       'Masuk',
    'login.noAccount':    'Belum punya akun?',
    'login.register':     'Daftar',
    'login.staffLink':    'Login sebagai Staff →',
    'login.error':        'Login gagal. Coba lagi.',

    // Register
    'register.title':     'Daftar Akun Baru',
    'register.subtitle':  'Amazing Toys Fair 2026',
    'register.name':      'Nama Lengkap',
    'register.namePh':    'Masukkan nama lengkap',
    'register.phone':     'Nomor Telepon',
    'register.phonePh':   '08xxxxxxxxxx',
    'register.email':     'Email (opsional)',
    'register.emailPh':   'email@contoh.com',
    'register.gender':    'Jenis Kelamin',
    'register.male':      'Laki-laki',
    'register.female':    'Perempuan',
    'register.other':     'Tidak disebutkan',
    'register.dob':          'Tanggal Lahir (opsional)',
    'register.dobHint':      'Pilih tanggal, bulan, dan tahun lahir',
    'register.submit':       'Daftar Sekarang',
    'register.hasAccount':   'Sudah punya akun?',
    'register.login':        'Masuk',
    'register.error':        'Pendaftaran gagal. Coba lagi.',
    'register.errName':      'Nama lengkap wajib diisi.',
    'register.errPhone':     'Nomor telepon wajib diisi.',
    'register.errPhoneFormat':'Format nomor tidak valid. Gunakan 08xxx atau +628xxx.',
    'register.errEmailRequired': 'Email wajib diisi.',
    'register.errEmail':     'Format email tidak valid.',
    'register.otpTitle':     'Verifikasi WhatsApp',
    'register.otpSubtitle':  'Kode 6 digit dikirim ke WhatsApp',
    'register.otpExpiry':    'Berlaku 5 menit',
    'register.otpResend':    'Kirim ulang OTP',
    'register.otpBack':      '← Kembali ke Formulir',
    'register.otpVerify':    'Verifikasi & Daftar',
    'register.otpSuccess':   'Akun berhasil dibuat! Selamat datang 🎉',

    // Badge status labels
    'badge.PENDING_APPROVAL': 'Menunggu Approval',
    'badge.PENDING':          'Menunggu',
    'badge.PAID':             'Dibayar',
    'badge.DONE':             'Selesai',
    'badge.CANCELLED':        'Dibatalkan',
    'badge.EXPIRED':          'Kadaluarsa',
    'badge.AVAILABLE':        'Tersedia',
    'badge.LOW_STOCK':        'Stok Terbatas',
    'badge.OUT_OF_STOCK':     'Habis',
    'badge.APPROVED':         'Disetujui',
    'badge.REJECTED':         'Ditolak',
    'badge.READY':            'Siap',
    'badge.PREPARING':        'Menyiapkan',
    'badge.RESERVED':         'Reserved',
    'badge.WAITING_PAYMENT':  'Menunggu Bayar',
    'badge.HANDED_OVER':      'Diserahkan',
    'badge.COMPLETED':        'Selesai',

    // Shell notification card
    'shell.readyToPay': 'Pesanan Siap Bayar!',
    'shell.viewQR':     'Lihat QR →',
    'shell.logout':     'Keluar',

    // Order tracking — public view
    'order.invalidLink':      'Link Tidak Valid',
    'order.paymentDone':      'Pembayaran Selesai!',
    'order.ordersFrom':       'Pesanan dari',
    'order.qrNA':             'QR tidak tersedia',
    'order.showQRToCashier':  'Tunjukkan QR ini ke kasir → kembali ke booth untuk ambil barang',
    'order.qrExpired':        'QR sudah kedaluwarsa',
    'order.validFor':         'Berlaku {time}',
    'order.collectBooth':     'Kembali ke booth {name} untuk mengambil barang Anda.',

    // Checkout extras
    'checkout.downloadQR': 'Simpan QR',

    // Product detail extras
    'product.helperModeNote':  'Pemesanan dilakukan melalui petugas booth. Silakan temui staf di lokasi.',
    'browse.wishlistFavHint':  'Klik ❤️ pada produk favoritmu!',

    // Helper page
    'helper.loadError':              'Gagal memuat produk booth.',
    'helper.minOneProduct':          'Pilih minimal satu produk.',
    'helper.searchBarcode':          'Cari nama produk atau scan barcode…',
    'helper.noProducts':             'Tidak ada produk.',
    'helper.displayOnly':            'Display Only',
    'helper.onHold':                 'On Hold',
    'helper.maxPerPerson':           'Maks {n}/orang',
    'helper.handoverError':          'Gagal konfirmasi serah terima.',
    'helper.noPaidOrders':           'Tidak ada order yang menunggu serah terima.',
    'helper.ordersWaitingHandover':  '{n} order menunggu serah terima',
    'helper.confirmHandover':        '✓ Konfirmasi Serah Terima',
    'helper.orderSummary':           'Ringkasan Order',
    'helper.noItemSelected':         'Belum ada item dipilih.',
    'helper.customerPhone':          'No. HP customer (opsional)',
    'helper.approveGenerateQR':      'Approve & Buat QR',
    'helper.refresh':                'Refresh',
    'helper.tabOrder':               'Buat Order',
    'helper.tabApproval':            'Antrian Approval',
    'helper.tabHistory':             'Riwayat Hari Ini',
    'helper.tabHandover':            'Serah Terima',
    'helper.pageTitle':              'Helper Booth',
    'helper.newOrderToast':          'Pesanan baru menunggu approval! Ketuk untuk review.',
    'helper.createOrderError':       'Gagal membuat order.',

    // Cashier page extras
    'cashier.posTitle':            'POS Langsung',
    'cashier.posDesc':             'Buat pesanan walk-in tanpa customer scan QR',
    'cashier.queueTab':            'Antrian',
    'cashier.processedTab':        'Sudah Diproses',
    'cashier.noQueue':             'Tidak ada antrian pembayaran.',
    'cashier.noTransactions':      'Belum ada transaksi hari ini.',
    'cashier.voucherPlaceholder':  'Kode voucher (opsional) — akan diterapkan otomatis',

    // Payment page
    'payment.cancelled':   'Transaksi sudah dibatalkan.',
    'payment.success':     'Pembayaran Berhasil!',
    'payment.method':      'Metode Pembayaran',
    'payment.methodLabel': 'Metode',
    'payment.cashReceived':'Uang Diterima (Rp)',
    'payment.change':      'Kembalian',
    'payment.paymentRef':  'Nomor Referensi / Approval Code',
    'payment.processBtn':  'Proses Pembayaran',
    'payment.addProduct':  'Tambah Produk',
    'payment.newTxn':      'Transaksi Baru',
    'payment.viewRecap':   'Lihat Rekap',
    'payment.applying':    'Menerapkan voucher...',
    'payment.stockLow':    'Terbatas',
    'payment.btnAdded':    '✓ Ditambahkan',
    'payment.btnAdd':      '+ Tambah',

    // Tenant — order queue
    'tenantOrders.title':            'Antrian Pesanan',
    'tenantOrders.refresh':          'Refresh',
    'tenantOrders.empty.title':      'Belum ada pesanan',
    'tenantOrders.empty.desc':       'Pesanan yang sudah dibayar akan muncul di sini',
    'tenantOrders.waiting':          'Menunggu Serah Terima ({count})',
    'tenantOrders.done':             'Selesai ({count})',
    'tenantOrders.handover':         'Serah Terima ✓',
    'tenantOrders.newOrder':         'Pesanan baru masuk: {id}',
    'tenantOrders.handoverOk':       'Serah terima berhasil!',
    'tenantOrders.handoverErr':      'Gagal serah terima',
    'tenantOrders.loadError':        'Gagal memuat pesanan.',
    'tenantOrders.todayNotifs':      'Notifikasi Hari Ini',
    'tenantOrders.unread':           'Belum Dibaca',
    'tenantOrders.searchPlaceholder':'Masukkan atau scan nomor transaksi...',
    'tenantOrders.retry':            'Coba lagi',
    'tenantOrders.notFound':         'Transaksi tidak ditemukan',
    'tenantOrders.clearSearch':      'Hapus pencarian',
    'tenantOrders.notifAriaLabel':   'Notifikasi pembayaran',

    // Tenant — dashboard
    'tenantDash.title':       'Dashboard Tenant',
    'tenantDash.revenue':     'Pendapatan Hari Ini',
    'tenantDash.orders':      'Total Pesanan',
    'tenantDash.done':        'Selesai',
    'tenantDash.pending':     'Menunggu',
    'tenantDash.topProducts': 'Produk Terlaris',
    'tenantDash.sold':        '{n} terjual',

    // Tenant — daily report
    'laporan.title':        'Laporan Harian',
    'laporan.from':         'Dari',
    'laporan.to':           'Sampai',
    'laporan.show':         'Tampilkan',
    'laporan.dateError':    "Tanggal 'Dari' tidak boleh melebihi 'Sampai'.",
    'laporan.sectionA':     'Detail Penjualan per Produk',
    'laporan.sectionB':     'Penjualan Harian',
    'laporan.tenant':       'Tenant: {name}',
    'laporan.noData':       'Tidak ada data untuk periode yang dipilih.',
    'laporan.col.no':       'No',
    'laporan.col.product':  'Nama Produk',
    'laporan.col.category': 'Kategori',
    'laporan.col.qtySold':  'Terjual',
    'laporan.col.price':    'Harga (IDR)',
    'laporan.col.total':    'Total (IDR)',
    'laporan.col.date':     'Tanggal',
    'laporan.col.txnCount': 'Total Transaksi',
    'laporan.col.revenue':  'Pendapatan (IDR)',

    // Tenant — stock report
    'stock.title':        'Laporan Stok Terakhir',
    'stock.search':       'Cari produk / ID / barcode...',
    'stock.showInactive': 'Tampilkan nonaktif',
    'stock.updatedAt':    'Diperbarui pukul',
    'stock.empty':        'Tidak ada produk ditemukan.',
    'stock.col.name':     'Nama',
    'stock.col.category': 'Kategori',
    'stock.col.price':    'Harga',
    'stock.col.status':   'Status',
    'stock.col.stock':    'Stok',
    'stock.col.photo':    'Foto',

    // Cashier — payment
    'cashier.title':      'Proses Pembayaran',
    'cashier.search':     'Cari Transaksi',
    'cashier.searchBtn':  'Cari',
    'cashier.recent':     'Transaksi Terakhir',
    'cashier.err409':     'Transaksi sudah dibayar.',
    'cashier.err410':     'Transaksi telah kadaluarsa.',
    'cashier.err404':     'Transaksi tidak ditemukan.',
    'cashier.errDefault': 'Gagal mencari transaksi.',

    // Cashier — recap
    'recap.title':      'Rekap Harian',
    'recap.txnCount':   'Total Transaksi',
    'recap.grandTotal': 'Grand Total',
    'recap.cash':       'Tunai (CASH)',
    'recap.qris':       'QRIS',
    'recap.edc':        'EDC',
    'recap.transfer':   'Transfer',
    'recap.txnList':    'Daftar Transaksi ({count})',
  },

  EN: {
    mapTitle:  'Our Location',
    mapEmpty:  'Map has not been configured yet. Contact the administrator.',
    mapClose:  'Close',

    'nav.catalog': 'Catalog',
    'nav.cart':    'Cart',
    'nav.orders':  'Orders',

    // Common
    'common.back':   'Back',
    'common.close':  'Close',
    'common.later':  'Later',
    'common.none':   'None',

    'search.placeholder':      'Search products...',
    'search.storePlaceholder': 'Search stores...',
    'filter.all':              'All',
    'filter.inStockOnly':      'In stock only',
    'filter.productCount':     '{count} products',
    'browse.allProducts':      'All Products',
    'browse.selectedProducts': 'Selected Products',
    'browse.items':            '{count} items',
    'browse.products':         '{count} products',
    'browse.backToStores':     '← Back to store list',
    'browse.byProduct':        '🏷️ By Product',
    'browse.byStore':          '🏪 By Store',
    'browse.noStores':         'No stores on this floor',
    'browse.tryOtherFloor':    'Try a different floor',
    'browse.searchWishlist':   'Search in wishlist...',
    'browse.myWishlist':       'My Wishlist',
    'browse.itemsSaved':       'items saved',
    'browse.wishlistEmpty':    'Wishlist is empty',
    'browse.noWishlistMatch':  'No products found in wishlist.',
    'browse.exploreCatalog':   'Explore Products',
    'browse.scanAddedToCart':  'added to cart',
    'browse.scanNotFound':     'Product not found. Try scanning again.',
    'browse.wishlistFavHint':  'Tap ❤️ on your favorite products!',
    'browse.scanQRTitle':      'Scan Product QR',
    'browse.scanQRHint':       'Point camera at product QR code',
    'product.notFound':        'No products found',
    'product.tryOther':        'Try a different category or keyword',
    'product.outOfStock':      'Out of Stock',
    'product.added':           '✓ Added',
    'product.addToCart':       '+ Cart',
    'product.loadMore':        'Load more',

    'product.notFoundDetail':   'Product not found.',
    'back':                     '← Back',
    'product.booth':            'Booth',
    'product.location':         'Location',
    'product.stock':            'Stock',
    'product.addedFull':        '✓ Added to Cart',
    'product.addToCartFull':    'Add to Cart',
    'product.detail.category':  'CATEGORY',
    'product.detail.description':'DESCRIPTION',
    'product.detail.noDesc':    'No product description available',
    'product.detail.floor':     'Floor {n}',
    'product.detail.added':     'Added',

    'cart.stockAvailablePrompt': 'Stock is available! Move to cart?',
    'cart.moveToCart':           'Move to Cart',
    'cart.stockAvailable':       '✓ In Stock',
    'cart.waitingForStock':      '⏳ Awaiting Stock',
    'cart.savedForLater':        'Saved for Later',
    'cart.itemCount':            '{count} items',
    'cart.voucherSection':       'Discount Voucher',
    'cart.waitingWarningTitle':  '{count} items awaiting stock confirmation',
    'cart.waitingWarningBody':   'Visit the booth to confirm, or proceed to checkout only for available items. Waiting items will be saved to Wishlist automatically.',
    'cart.helperModeWarning':    'Helper Input mode is active. Orders must be placed through booth staff.',
    'cart.approveModeWarning':   'Your order will await booth staff approval. Stock and timer start after approval.',
    'cart.itemLimitWarning':     'Maximum {max} items per order. Currently {current} items — reduce before checkout.',
    'cart.subtotal':             'Subtotal',
    'cart.discount':             'Discount',
    'cart.taxLine':              'VAT {rate}%',
    'cart.estimatedTotal':       'Estimated total ({count} available items)',
    'cart.exceedsLimit':         'Exceeds limit',
    'cart.contactBooth':         'Contact booth staff',
    'cart.submitForApproval':    'Submit for Approval',
    'cart.orderAvailable':       'Order Available Items ({count} items)',
    'cart.allItemsWaiting':      'All items awaiting confirmation',
    'cart.unconfirmedNote':      'Not confirmed by booth · ask directly or remove',
    'cart.approvalTitle':        'Some items have not been stock-confirmed',
    'cart.approvalDesc':         'The following items are still awaiting availability confirmation from the booth.',
    'cart.readyToProcess':       'Ready to Process',
    'cart.noItems':              'None',
    'cart.awaitingConfirmation': 'Awaiting Confirmation',
    'cart.onHoldSavedNote':      'Items awaiting confirmation will be saved to Wishlist — not deleted. You will be notified when stock is available.',
    'cart.totalReadyItems':      'Total {count} items ready to process',
    'cart.allOnHold':            'All items are awaiting stock confirmation.',
    'cart.checkoutUnavailable':  'Checkout cannot proceed at this time.',
    'cart.continueCheckout':     'Yes, Continue Checkout',
    'cart.title':                'Cart ({count} item)',
    'cart.empty.title':          'Cart is empty',
    'cart.empty.desc':           'Add products from the catalog',
    'cart.toCatalog':            'To Catalog →',
    'cart.total':                'Total Payment',
    'cart.pendingNote':          'Order valid for 30 minutes. Please pay at the cashier.',
    'cart.checkout':             'Place Order',
    'cart.checkoutError':        'Checkout failed. Please try again.',

    'orders.title':       'Order History',
    'orders.empty.title': 'No orders yet',
    'orders.empty.desc':  'Start shopping in the catalog!',
    'orders.toCatalog':   'To Catalog →',

    'order.notFound':     'Order not found.',
    'order.backHistory':  '← Order History',
    'order.showQR':       'Show this QR code to the cashier',
    'order.cancelBtn':    'Cancel Order',
    'order.cancelTitle':  'Cancel Order?',
    'order.cancelBody':   'Order {id} will be cancelled and stock restored.',
    'order.cancelNo':     'No',
    'order.cancelYes':    'Yes, Cancel',
    'order.refresh':      'Refresh',
    'order.refreshing':   'Refreshing...',

    // Payment confirmed (C7)
    'confirmed.title':         'Payment Successful!',
    'confirmed.subtitle':      'Your items are being prepared at the booths',
    'confirmed.txnId':         'Transaction ID',
    'confirmed.totalPaid':     'Total Paid',
    'confirmed.payment':       'Payment',
    'confirmed.datetime':      'Date & Time',
    'confirmed.nonReturnable': 'All sales are final and non-returnable.',
    'confirmed.cta':           'View Receipt & Pickup Slip',
    'confirmed.ctaHint':       'Collect items at tenant booths',

    // Receipt & pickup (C8)
    'receipt.sectionReceipt': 'PAYMENT RECEIPT',
    'receipt.sectionPickup':  'PICKUP INSTRUCTIONS',
    'receipt.total':          'Total',
    'receipt.done':           'Done ✓',
    'receipt.ready':          'Ready',
    'receipt.cta':            'Track Item Pickup',

    // Pickup status (C9)
    'pickup.infoBanner':   'Visit each booth and show your QR code. Items update automatically.',
    'pickup.done':         'Done ✓',
    'pickup.ready':        'Ready',
    'pickup.preparing':    'Preparing',
    'pickup.collected':    'Collected',
    'pickup.items':        'items',
    'pickup.allDone':      'All items collected! 🎉',
    'pickup.showBarcode':  'Show Transaction Barcode',
    'pickup.modalTitle':   'Transaction Barcode',

    'checkout.created':  'Order Created!',
    'checkout.showQR':   'Show this QR code to the cashier for payment',
    'checkout.qrMissing':'QR Code unavailable',
    'checkout.txnId':    'Transaction ID',
    'checkout.total':    'Total',
    'checkout.payIn':    '⏰ Pay in {mins}:{secs} minutes',
    'checkout.expired':  '⚠️ Order has expired',
    'checkout.track':    'Track Order',
    'checkout.continue': 'Continue Shopping',

    'login.title':        'Login',
    'login.subtitle':     'Amazing Toys Fair 2026',
    'login.phone':        'Phone Number',
    'login.phonePh':      '08xxxxxxxxxx',
    'login.submit':       'Login',
    'login.noAccount':    "Don't have an account?",
    'login.register':     'Register',
    'login.staffLink':    'Login as Staff →',
    'login.error':        'Login failed. Please try again.',

    'register.title':     'Create New Account',
    'register.subtitle':  'Amazing Toys Fair 2026',
    'register.name':      'Full Name',
    'register.namePh':    'Enter full name',
    'register.phone':     'Phone Number',
    'register.phonePh':   '08xxxxxxxxxx',
    'register.email':     'Email (optional)',
    'register.emailPh':   'email@example.com',
    'register.gender':    'Gender',
    'register.male':      'Male',
    'register.female':    'Female',
    'register.other':     'Prefer not to say',
    'register.dob':          'Date of Birth (optional)',
    'register.dobHint':      'Select day, month, and birth year',
    'register.submit':       'Register Now',
    'register.hasAccount':   'Already have an account?',
    'register.login':        'Login',
    'register.error':        'Registration failed. Please try again.',
    'register.errName':      'Full name is required.',
    'register.errPhone':     'Phone number is required.',
    'register.errPhoneFormat':'Invalid format. Use 08xxx or +628xxx.',
    'register.errEmailRequired': 'Email is required.',
    'register.errEmail':     'Invalid email format.',
    'register.otpTitle':     'WhatsApp Verification',
    'register.otpSubtitle':  '6-digit code sent to WhatsApp',
    'register.otpExpiry':    'Valid for 5 minutes',
    'register.otpResend':    'Resend OTP',
    'register.otpBack':      '← Back to Form',
    'register.otpVerify':    'Verify & Register',
    'register.otpSuccess':   'Account created! Welcome 🎉',

    'badge.PENDING_APPROVAL': 'Awaiting Approval',
    'badge.PENDING':          'Pending',
    'badge.PAID':             'Paid',
    'badge.DONE':             'Done',
    'badge.CANCELLED':        'Cancelled',
    'badge.EXPIRED':          'Expired',
    'badge.AVAILABLE':        'Available',
    'badge.LOW_STOCK':        'Limited Stock',
    'badge.OUT_OF_STOCK':     'Out of Stock',
    'badge.APPROVED':         'Approved',
    'badge.REJECTED':         'Rejected',
    'badge.READY':            'Ready',
    'badge.PREPARING':        'Preparing',
    'badge.RESERVED':         'Reserved',
    'badge.WAITING_PAYMENT':  'Waiting for Payment',
    'badge.HANDED_OVER':      'Handed Over',
    'badge.COMPLETED':        'Completed',

    // Shell notification card
    'shell.readyToPay': 'Order Ready to Pay!',
    'shell.viewQR':     'View QR →',
    'shell.logout':     'Logout',

    // Order tracking — public view
    'order.invalidLink':      'Invalid Link',
    'order.paymentDone':      'Payment Complete!',
    'order.ordersFrom':       'Order from',
    'order.qrNA':             'QR unavailable',
    'order.showQRToCashier':  'Show this QR to cashier → return to booth to collect items',
    'order.qrExpired':        'QR has expired',
    'order.validFor':         'Valid {time}',
    'order.collectBooth':     'Return to booth {name} to collect your items.',

    // Checkout extras
    'checkout.downloadQR': 'Save QR',

    // Product detail extras
    'product.helperModeNote':  'Orders are placed through booth staff. Please see staff at the location.',
    'browse.wishlistFavHint':  'Tap ❤️ on your favorite products!',

    // Helper page
    'helper.loadError':              'Failed to load booth products.',
    'helper.minOneProduct':          'Please select at least one product.',
    'helper.searchBarcode':          'Search product name or scan barcode…',
    'helper.noProducts':             'No products found.',
    'helper.displayOnly':            'Display Only',
    'helper.onHold':                 'On Hold',
    'helper.maxPerPerson':           'Max {n}/person',
    'helper.handoverError':          'Failed to confirm handover.',
    'helper.noPaidOrders':           'No orders waiting for handover.',
    'helper.ordersWaitingHandover':  '{n} orders awaiting handover',
    'helper.confirmHandover':        '✓ Confirm Handover',
    'helper.orderSummary':           'Order Summary',
    'helper.noItemSelected':         'No items selected.',
    'helper.customerPhone':          'Customer Phone (optional)',
    'helper.approveGenerateQR':      'Approve & Generate QR',
    'helper.refresh':                'Refresh',
    'helper.tabOrder':               'Create Order',
    'helper.tabApproval':            'Approval Queue',
    'helper.tabHistory':             "Today's History",
    'helper.tabHandover':            'Handover',
    'helper.pageTitle':              'Helper Booth',
    'helper.newOrderToast':          'New order waiting for approval! Tap to review.',
    'helper.createOrderError':       'Failed to create order.',

    // Cashier page extras
    'cashier.posTitle':            'Direct POS',
    'cashier.posDesc':             'Create walk-in orders without customer QR scan',
    'cashier.queueTab':            'Queue',
    'cashier.processedTab':        'Processed',
    'cashier.noQueue':             'No payment queue.',
    'cashier.noTransactions':      'No transactions today.',
    'cashier.voucherPlaceholder':  'Voucher code (optional) — applied automatically',

    // Payment page
    'payment.cancelled':   'Transaction has been cancelled.',
    'payment.success':     'Payment Successful!',
    'payment.method':      'Payment Method',
    'payment.methodLabel': 'Method',
    'payment.cashReceived':'Cash Received (Rp)',
    'payment.change':      'Change',
    'payment.paymentRef':  'Reference No. / Approval Code',
    'payment.processBtn':  'Process Payment',
    'payment.addProduct':  'Add Product',
    'payment.newTxn':      'New Transaction',
    'payment.viewRecap':   'View Recap',
    'payment.applying':    'Applying voucher...',
    'payment.stockLow':    'Limited',
    'payment.btnAdded':    '✓ Added',
    'payment.btnAdd':      '+ Add',

    // Tenant — order queue
    'tenantOrders.title':            'Order Queue',
    'tenantOrders.refresh':          'Refresh',
    'tenantOrders.empty.title':      'No orders yet',
    'tenantOrders.empty.desc':       'Paid orders will appear here',
    'tenantOrders.waiting':          'Awaiting Handover ({count})',
    'tenantOrders.done':             'Done ({count})',
    'tenantOrders.handover':         'Hand Over ✓',
    'tenantOrders.newOrder':         'New order received: {id}',
    'tenantOrders.handoverOk':       'Handover successful!',
    'tenantOrders.handoverErr':      'Handover failed',
    'tenantOrders.loadError':        'Failed to load orders.',
    'tenantOrders.todayNotifs':      "Today's Notifications",
    'tenantOrders.unread':           'Unread',
    'tenantOrders.searchPlaceholder':'Enter or scan transaction number...',
    'tenantOrders.retry':            'Try again',
    'tenantOrders.notFound':         'Transaction not found',
    'tenantOrders.clearSearch':      'Clear search',
    'tenantOrders.notifAriaLabel':   'Payment notifications',

    // Tenant — dashboard
    'tenantDash.title':       'Tenant Dashboard',
    'tenantDash.revenue':     "Today's Revenue",
    'tenantDash.orders':      'Total Orders',
    'tenantDash.done':        'Done',
    'tenantDash.pending':     'Pending',
    'tenantDash.topProducts': 'Top Products',
    'tenantDash.sold':        '{n} sold',

    // Tenant — daily report
    'laporan.title':        'Daily Report',
    'laporan.from':         'From',
    'laporan.to':           'To',
    'laporan.show':         'Show',
    'laporan.dateError':    "'From' date cannot be later than 'To' date.",
    'laporan.sectionA':     'Sales Detail by Product',
    'laporan.sectionB':     'Daily Sales',
    'laporan.tenant':       'Tenant: {name}',
    'laporan.noData':       'No data for the selected period.',
    'laporan.col.no':       'No',
    'laporan.col.product':  'Product Name',
    'laporan.col.category': 'Category',
    'laporan.col.qtySold':  'Qty Sold',
    'laporan.col.price':    'Price (IDR)',
    'laporan.col.total':    'Total (IDR)',
    'laporan.col.date':     'Date',
    'laporan.col.txnCount': 'Transactions',
    'laporan.col.revenue':  'Revenue (IDR)',

    // Tenant — stock report
    'stock.title':        'Last Stock Update Report',
    'stock.search':       'Search product / ID / barcode...',
    'stock.showInactive': 'Show inactive',
    'stock.updatedAt':    'Updated at',
    'stock.empty':        'No products found.',
    'stock.col.name':     'Name',
    'stock.col.category': 'Category',
    'stock.col.price':    'Price',
    'stock.col.status':   'Status',
    'stock.col.stock':    'Stock',
    'stock.col.photo':    'Photo',

    // Cashier — payment
    'cashier.title':      'Process Payment',
    'cashier.search':     'Find Transaction',
    'cashier.searchBtn':  'Search',
    'cashier.recent':     'Recent Transactions',
    'cashier.err409':     'Transaction already paid.',
    'cashier.err410':     'Transaction has expired.',
    'cashier.err404':     'Transaction not found.',
    'cashier.errDefault': 'Failed to find transaction.',

    // Cashier — recap
    'recap.title':      'Daily Recap',
    'recap.txnCount':   'Total Transactions',
    'recap.grandTotal': 'Grand Total',
    'recap.cash':       'Cash',
    'recap.qris':       'QRIS',
    'recap.edc':        'EDC',
    'recap.transfer':   'Transfer',
    'recap.txnList':    'Transactions ({count})',
  },

  ZH: {
    mapTitle:  '我们的位置',
    mapEmpty:  '地图尚未配置，请联系管理员。',
    mapClose:  '关闭',

    'nav.catalog': '目录',
    'nav.cart':    '购物车',
    'nav.orders':  '订单',

    // Common
    'common.back':   '返回',
    'common.close':  '关闭',
    'common.later':  '稍后',
    'common.none':   '无',

    'search.placeholder':      '搜索产品...',
    'search.storePlaceholder': '搜索商店...',
    'filter.all':              '全部',
    'filter.inStockOnly':      '仅有库存',
    'filter.productCount':     '{count} 件产品',
    'browse.allProducts':      '全部产品',
    'browse.selectedProducts': '所选产品',
    'browse.items':            '{count} 件',
    'browse.products':         '{count} 件产品',
    'browse.backToStores':     '← 返回商店列表',
    'browse.byProduct':        '🏷️ 按产品',
    'browse.byStore':          '🏪 按商店',
    'browse.noStores':         '此楼层没有商店',
    'browse.tryOtherFloor':    '试试其他楼层',
    'browse.searchWishlist':   '在心愿单中搜索...',
    'browse.myWishlist':       '我的心愿单',
    'browse.itemsSaved':       '件已保存',
    'browse.wishlistEmpty':    '心愿单是空的',
    'browse.noWishlistMatch':  '心愿单中未找到产品。',
    'browse.exploreCatalog':   '探索产品',
    'browse.scanAddedToCart':  '已加入购物车',
    'browse.scanNotFound':     '未找到产品，请重新扫描。',
    'browse.wishlistFavHint':  '点击 ❤️ 收藏您喜欢的产品！',
    'browse.scanQRTitle':      '扫描产品二维码',
    'browse.scanQRHint':       '将相机对准产品二维码',
    'product.notFound':        '未找到产品',
    'product.tryOther':        '请换个分类或关键词',
    'product.outOfStock':      '缺货',
    'product.added':           '✓ 已添加',
    'product.addToCart':       '+ 加购',
    'product.loadMore':        '加载更多',

    'product.notFoundDetail':   '未找到产品。',
    'back':                     '← 返回',
    'product.booth':            '摊位',
    'product.location':         '位置',
    'product.stock':            '库存',
    'product.addedFull':        '✓ 已加入购物车',
    'product.addToCartFull':    '加入购物车',
    'product.detail.category':  '类别',
    'product.detail.description':'描述',
    'product.detail.noDesc':    '暂无产品描述',
    'product.detail.floor':     '{n}楼',
    'product.detail.added':     '已添加',

    'cart.stockAvailablePrompt': '库存已到！移至购物车？',
    'cart.moveToCart':           '移至购物车',
    'cart.stockAvailable':       '✓ 有货',
    'cart.waitingForStock':      '⏳ 等待库存',
    'cart.savedForLater':        '稍后购买',
    'cart.itemCount':            '{count} 件',
    'cart.voucherSection':       '折扣优惠券',
    'cart.waitingWarningTitle':  '{count} 件商品等待库存确认',
    'cart.waitingWarningBody':   '前往摊位确认，或仅对可用商品结账。等待中的商品将自动保存到心愿单。',
    'cart.helperModeWarning':    'Helper Input模式已激活，订单只能通过摊位工作人员下单。',
    'cart.approveModeWarning':   '您的订单将等待摊位工作人员审批，库存和计时器在审批后开始。',
    'cart.itemLimitWarning':     '每单最多 {max} 件，当前 {current} 件 — 结账前请减少数量。',
    'cart.subtotal':             '小计',
    'cart.discount':             '折扣',
    'cart.taxLine':              '增值税 {rate}%',
    'cart.estimatedTotal':       '预计总额（{count} 件可用）',
    'cart.exceedsLimit':         '超出限制',
    'cart.contactBooth':         '联系摊位工作人员',
    'cart.submitForApproval':    '提交审批',
    'cart.orderAvailable':       '下单可用商品（{count} 件）',
    'cart.allItemsWaiting':      '所有商品等待确认',
    'cart.unconfirmedNote':      '未经摊位确认 · 请直接询问或删除',
    'cart.approvalTitle':        '部分商品尚未确认库存',
    'cart.approvalDesc':         '以下商品仍在等待摊位的库存确认。',
    'cart.readyToProcess':       '可以处理',
    'cart.noItems':              '无',
    'cart.awaitingConfirmation': '等待确认',
    'cart.onHoldSavedNote':      '等待确认的商品将保存到心愿单 — 不会被删除。库存可用时您将收到通知。',
    'cart.totalReadyItems':      '共 {count} 件可处理',
    'cart.allOnHold':            '所有商品正在等待库存确认。',
    'cart.checkoutUnavailable':  '目前无法继续结账。',
    'cart.continueCheckout':     '是，继续结账',
    'cart.title':                '购物车 ({count} 件)',
    'cart.empty.title':          '购物车是空的',
    'cart.empty.desc':           '从目录添加产品',
    'cart.toCatalog':            '去目录 →',
    'cart.total':                '付款总额',
    'cart.pendingNote':          '订单有效期为30分钟，请尽快到收银台付款。',
    'cart.checkout':             '下单',
    'cart.checkoutError':        '结账失败，请重试。',

    'orders.title':       '订单历史',
    'orders.empty.title': '暂无订单',
    'orders.empty.desc':  '快去目录购物吧！',
    'orders.toCatalog':   '去目录 →',

    'order.notFound':     '未找到订单。',
    'order.backHistory':  '← 订单历史',
    'order.showQR':       '请将此二维码出示给收银员',
    'order.cancelBtn':    '取消订单',
    'order.cancelTitle':  '取消订单？',
    'order.cancelBody':   '订单 {id} 将被取消，库存将恢复。',
    'order.cancelNo':     '否',
    'order.cancelYes':    '是，取消',
    'order.refresh':      '刷新',
    'order.refreshing':   '刷新中...',

    // Payment confirmed (C7)
    'confirmed.title':         '付款成功！',
    'confirmed.subtitle':      '您的商品正在各摊位准备中',
    'confirmed.txnId':         '交易编号',
    'confirmed.totalPaid':     '支付总额',
    'confirmed.payment':       '支付方式',
    'confirmed.datetime':      '日期和时间',
    'confirmed.nonReturnable': '所有销售均为最终决定，不可退货。',
    'confirmed.cta':           '查看收据和取货单',
    'confirmed.ctaHint':       '请前往摊位领取商品',

    // Receipt & pickup (C8)
    'receipt.sectionReceipt': '付款收据',
    'receipt.sectionPickup':  '取货说明',
    'receipt.total':          '合计',
    'receipt.done':           '已完成 ✓',
    'receipt.ready':          '已备好',
    'receipt.cta':            '追踪取货状态',

    // Pickup status (C9)
    'pickup.infoBanner':   '前往每个摊位并出示您的二维码，状态将自动更新。',
    'pickup.done':         '已完成 ✓',
    'pickup.ready':        '已备好',
    'pickup.preparing':    '准备中',
    'pickup.collected':    '已领取',
    'pickup.items':        '件商品',
    'pickup.allDone':      '所有商品已领取！🎉',
    'pickup.showBarcode':  '显示交易条码',
    'pickup.modalTitle':   '交易条码',

    'checkout.created':  '订单已创建！',
    'checkout.showQR':   '请将此二维码出示给收银员付款',
    'checkout.qrMissing':'二维码不可用',
    'checkout.txnId':    '交易编号',
    'checkout.total':    '总计',
    'checkout.payIn':    '⏰ 请在 {mins}:{secs} 分钟内付款',
    'checkout.expired':  '⚠️ 订单已过期',
    'checkout.track':    '追踪订单',
    'checkout.continue': '继续购物',

    'login.title':        '登录',
    'login.subtitle':     'Amazing Toys Fair 2026',
    'login.phone':        '手机号',
    'login.phonePh':      '08xxxxxxxxxx',
    'login.submit':       '登录',
    'login.noAccount':    '没有账户？',
    'login.register':     '注册',
    'login.staffLink':    '员工登录 →',
    'login.error':        '登录失败，请重试。',

    'register.title':     '创建新账户',
    'register.subtitle':  'Amazing Toys Fair 2026',
    'register.name':      '全名',
    'register.namePh':    '输入全名',
    'register.phone':     '手机号',
    'register.phonePh':   '08xxxxxxxxxx',
    'register.email':     '邮箱（可选）',
    'register.emailPh':   'email@example.com',
    'register.gender':    '性别',
    'register.male':      '男',
    'register.female':    '女',
    'register.other':     '不透露',
    'register.dob':          '出生日期（可选）',
    'register.dobHint':      '请选择出生的日、月、年',
    'register.submit':       '立即注册',
    'register.hasAccount':   '已有账户？',
    'register.login':        '登录',
    'register.error':        '注册失败，请重试。',
    'register.errName':      '全名为必填项。',
    'register.errPhone':     '手机号为必填项。',
    'register.errPhoneFormat':'格式无效，请使用 08xxx 或 +628xxx。',
    'register.errEmailRequired': '邮箱为必填项。',
    'register.errEmail':     '邮箱格式无效。',
    'register.otpTitle':     'WhatsApp 验证',
    'register.otpSubtitle':  '6位验证码已发送至WhatsApp',
    'register.otpExpiry':    '有效期5分钟',
    'register.otpResend':    '重新发送验证码',
    'register.otpBack':      '← 返回表单',
    'register.otpVerify':    '验证并注册',
    'register.otpSuccess':   '账户创建成功！欢迎 🎉',

    'badge.PENDING_APPROVAL': '等待审批',
    'badge.PENDING':          '待处理',
    'badge.PAID':             '已付款',
    'badge.DONE':             '完成',
    'badge.CANCELLED':        '已取消',
    'badge.EXPIRED':          '已过期',
    'badge.AVAILABLE':        '有库存',
    'badge.LOW_STOCK':        '库存有限',
    'badge.OUT_OF_STOCK':     '缺货',
    'badge.APPROVED':         '已批准',
    'badge.REJECTED':         '已拒绝',
    'badge.READY':            '已就绪',
    'badge.PREPARING':        '准备中',
    'badge.RESERVED':         '已预留',
    'badge.WAITING_PAYMENT':  '等待付款',
    'badge.HANDED_OVER':      '已交接',
    'badge.COMPLETED':        '已完成',

    // Shell notification card
    'shell.readyToPay': '订单待付款！',
    'shell.viewQR':     '查看二维码 →',
    'shell.logout':     '退出',

    // Order tracking — public view
    'order.invalidLink':      '链接无效',
    'order.paymentDone':      '付款完成！',
    'order.ordersFrom':       '订单来自',
    'order.qrNA':             '二维码不可用',
    'order.showQRToCashier':  '将此二维码出示给收银员 → 返回摊位取货',
    'order.qrExpired':        '二维码已过期',
    'order.validFor':         '有效期 {time}',
    'order.collectBooth':     '请返回摊位 {name} 领取您的商品。',

    // Checkout extras
    'checkout.downloadQR': '保存二维码',

    // Product detail extras
    'product.helperModeNote':  '订单通过摊位工作人员处理，请在现场联系工作人员。',
    'browse.wishlistFavHint':  '点击 ❤️ 收藏您喜欢的产品！',

    // Helper page
    'helper.loadError':              '加载摊位产品失败。',
    'helper.minOneProduct':          '请至少选择一件产品。',
    'helper.searchBarcode':          '搜索产品名称或扫描条码…',
    'helper.noProducts':             '没有产品。',
    'helper.displayOnly':            'Display Only',
    'helper.onHold':                 'On Hold',
    'helper.maxPerPerson':           '最多 {n}/人',
    'helper.handoverError':          '确认移交失败。',
    'helper.noPaidOrders':           '没有等待移交的订单。',
    'helper.ordersWaitingHandover':  '{n} 个订单等待移交',
    'helper.confirmHandover':        '✓ 确认移交',
    'helper.orderSummary':           '订单摘要',
    'helper.noItemSelected':         '尚未选择商品。',
    'helper.customerPhone':          '客户电话（可选）',
    'helper.approveGenerateQR':      '批准并生成QR',
    'helper.refresh':                '刷新',
    'helper.tabOrder':               '创建订单',
    'helper.tabApproval':            '待审批队列',
    'helper.tabHistory':             '今日历史',
    'helper.tabHandover':            '移交',
    'helper.pageTitle':              '助手台',
    'helper.newOrderToast':          '新订单等待审批！点击查看。',
    'helper.createOrderError':       '创建订单失败。',

    // Cashier page extras
    'cashier.posTitle':            '直接POS',
    'cashier.posDesc':             '无需顾客扫码即可创建到店订单',
    'cashier.queueTab':            '队列',
    'cashier.processedTab':        '已处理',
    'cashier.noQueue':             '没有待付款队列。',
    'cashier.noTransactions':      '今天还没有交易。',
    'cashier.voucherPlaceholder':  '优惠券代码（可选）— 自动应用',

    // Payment page
    'payment.cancelled':   '交易已取消。',
    'payment.success':     '付款成功！',
    'payment.method':      '支付方式',
    'payment.methodLabel': '方式',
    'payment.cashReceived':'收到现金 (Rp)',
    'payment.change':      '找零',
    'payment.paymentRef':  '参考号 / 批准码',
    'payment.processBtn':  '处理付款',
    'payment.addProduct':  '添加产品',
    'payment.newTxn':      '新交易',
    'payment.viewRecap':   '查看汇总',
    'payment.applying':    '正在应用优惠券...',
    'payment.stockLow':    '有限',
    'payment.btnAdded':    '✓ 已添加',
    'payment.btnAdd':      '+ 添加',

    // Tenant — order queue
    'tenantOrders.title':            '订单队列',
    'tenantOrders.refresh':          '刷新',
    'tenantOrders.empty.title':      '暂无订单',
    'tenantOrders.empty.desc':       '已付款的订单将显示在这里',
    'tenantOrders.waiting':          '等待交接 ({count})',
    'tenantOrders.done':             '已完成 ({count})',
    'tenantOrders.handover':         '确认交接 ✓',
    'tenantOrders.newOrder':         '新订单到来：{id}',
    'tenantOrders.handoverOk':       '交接成功！',
    'tenantOrders.handoverErr':      '交接失败',
    'tenantOrders.loadError':        '加载订单失败。',
    'tenantOrders.todayNotifs':      '今日通知',
    'tenantOrders.unread':           '未读',
    'tenantOrders.searchPlaceholder':'输入或扫描交易号...',
    'tenantOrders.retry':            '重试',
    'tenantOrders.notFound':         '未找到交易',
    'tenantOrders.clearSearch':      '清除搜索',
    'tenantOrders.notifAriaLabel':   '支付通知',

    // Tenant — dashboard
    'tenantDash.title':       '租户仪表板',
    'tenantDash.revenue':     '今日收入',
    'tenantDash.orders':      '总订单数',
    'tenantDash.done':        '已完成',
    'tenantDash.pending':     '待处理',
    'tenantDash.topProducts': '热销产品',
    'tenantDash.sold':        '已售 {n}',

    // Tenant — daily report
    'laporan.title':        '日报',
    'laporan.from':         '从',
    'laporan.to':           '至',
    'laporan.show':         '显示',
    'laporan.dateError':    '起始日期不能晚于结束日期。',
    'laporan.sectionA':     '按产品销售明细',
    'laporan.sectionB':     '每日销售',
    'laporan.tenant':       '租户：{name}',
    'laporan.noData':       '所选时间段内无数据。',
    'laporan.col.no':       '序号',
    'laporan.col.product':  '产品名称',
    'laporan.col.category': '分类',
    'laporan.col.qtySold':  '已售数量',
    'laporan.col.price':    '单价 (IDR)',
    'laporan.col.total':    '合计 (IDR)',
    'laporan.col.date':     '日期',
    'laporan.col.txnCount': '交易数',
    'laporan.col.revenue':  '收入 (IDR)',

    // Tenant — stock report
    'stock.title':        '最新库存报告',
    'stock.search':       '搜索产品 / ID / 条形码...',
    'stock.showInactive': '显示非活跃',
    'stock.updatedAt':    '更新时间',
    'stock.empty':        '未找到产品。',
    'stock.col.name':     '名称',
    'stock.col.category': '分类',
    'stock.col.price':    '价格',
    'stock.col.status':   '状态',
    'stock.col.stock':    '库存',
    'stock.col.photo':    '照片',

    // Cashier — payment
    'cashier.title':      '处理付款',
    'cashier.search':     '查找交易',
    'cashier.searchBtn':  '搜索',
    'cashier.recent':     '最近交易',
    'cashier.err409':     '该交易已付款。',
    'cashier.err410':     '该交易已过期。',
    'cashier.err404':     '未找到交易。',
    'cashier.errDefault': '查找交易失败。',

    // Cashier — recap
    'recap.title':      '每日汇总',
    'recap.txnCount':   '总交易数',
    'recap.grandTotal': '总计',
    'recap.cash':       '现金',
    'recap.qris':       'QRIS',
    'recap.edc':        'EDC',
    'recap.transfer':   '转账',
    'recap.txnList':    '交易列表 ({count})',
  },
};

// ── Supported languages ───────────────────────────────────────────────────────

export const SUPPORTED_LANGS = [
  { code: 'ID', label: 'ID' },
  { code: 'EN', label: 'EN' },
  { code: 'ZH', label: '中文' },
];

const STORAGE_KEY = 'sos_lang';

// ── Context ───────────────────────────────────────────────────────────────────

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLangState] = useState(
    () => localStorage.getItem(STORAGE_KEY) || 'EN'
  );

  function setLang(code) {
    localStorage.setItem(STORAGE_KEY, code);
    setLangState(code);
  }

  // t(key) — simple lookup with optional {var} interpolation
  // t(key, { count: 5 }) → replaces {count} in the string
  function t(key, vars = {}) {
    let str = T[lang]?.[key] ?? T.ID[key] ?? key;
    if (vars && Object.keys(vars).length > 0) {
      str = Object.entries(vars).reduce(
        (s, [k, v]) => s.replace(new RegExp(`\\{${k}\\}`, 'g'), v),
        str
      );
    }
    return str;
  }

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLang must be used inside LangProvider');
  return ctx;
}
